### Movie index 

GET http://localhost:3000/movies/

### Movie create

POST http://localhost:3000/movies/
Content-Type: application/json

{
  "title":  "Anchorman",
  "year": 2005,
  "plot": "Ron Burgundy is San Diego's top reporter",
  "director": "Hollywood Joe"
}

### Movie show

GET http://localhost:3000/movies/6

### Movie update

PATCH http://localhost:3000/movies/6
Content-Type: application/json

{
  "director": "Action Bronson"
}

### Movie destroy

DELETE http://localhost:3000/movies/1

### Actor show

GET http://localhost:3000/actors/5