@jwt = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NTMyNDA5MzB9.UKZbqH5iqtBXJZvChKuY7sTkKpSHlSG2xq1B11PQskU

### Movie index 

GET http://localhost:3000/movies/

### Movie create

POST http://localhost:3000/movies/
Authorization: Bearer {{jwt}}
Content-Type: application/json

{
  "title":  "Anchorman",
  "year": 2005,
  "plot": "Ron Burgundy is San Diego's top reporter",
  "director": "Hollywood Joe"
}

### Movie show

GET http://localhost:3000/movies/6

### Movie update

PATCH http://localhost:3000/movies/6
Content-Type: application/json
Authorization: Bearer {{jwt}}

{
  "director": "Action Bronson"
}

### Movie destroy

DELETE http://localhost:3000/movies/1
Authorization: Bearer {{jwt}}

### Actor show

GET http://localhost:3000/actors/5

### Users create (signup)
POST http://localhost:3000/users.json
Content-Type: application/json

{
  "name": "Test3 name",
  "email": "test3@test.com",
  "password": "password",
  "password_confirmation": "password"
}

### Sessions create (login)
POST http://localhost:3000/sessions.json
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "password"
}

# ### Photos create
# POST http://localhost:3000/photos.json
# Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyIjozLCJleHAiOjE2Mjk5OTI4NjR9.G2ExsrDYn3oE0vJkvm4T6Po2GbNpH5cqTEaVPVuK_MA
# Content-Type: application/json

# {
#   "name": "Test name",
#   "width": 640,
#   "height": 480
# }