@jwt = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NTQ3ODU4OTF9.b1WHbYEV2bYIuZEyPqge58A3UlKuz3KX3hMUmUO3Clc

### Movie index 

GET http://localhost:3000/movies.json

### Movie create

POST http://localhost:3000/movies/
Authorization: Bearer {{jwt}}
Content-Type: application/json

{
  "title":  "Anchorman 2",
  "year": 2005,
  "plot": "Ron Burgundy is San Diego's top reporter",
  "director": "Hollywood Joe"
}

### Movie show

GET http://localhost:3000/movies/7.json

### Movie update

PATCH http://localhost:3000/movies/6
Content-Type: application/json
Authorization: Bearer {{jwt}}

{
  "director": "Action Bronson"
}

### Movie destroy

DELETE http://localhost:3000/movies/8
Authorization: Bearer {{jwt}}

### Actor show

GET http://localhost:3000/actors/5

### Users create (signup)
POST http://localhost:3000/users.json
Content-Type: application/json

{
  "name": "Test3 name",
  "email": "test3@test.com",
  "password": "password",
  "password_confirmation": "password"
}

### Sessions create (login)
POST http://localhost:3000/sessions.json
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "password"
}